#!/bin/bash
#install OpenDaylight

# 1. install Hydrogen base
hydrogenVersion="0.1.1"
wget 'https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/distributions-base/'${hydrogenVersion}'/distributions-base-'${hydrogenVersion}'-osgipackage.zip'
unzip distributions-base-${hydrogenVersion}-osgipackage.zip
rm distributions-base-${hydrogenVersion}-osgipackage.zip

#to run to get osgi> 
#./opendaylight/run.sh


# 2. install openflow plugin - drop test
openflowPluginVersion="0.1.0-SNAPSHOT"
wget 'https://jenkins.opendaylight.org/openflowplugin/job/openflowplugin-merge/lastSuccessfulBuild/org.opendaylight.openflowplugin$drop-test/artifact/org.opendaylight.openflowplugin/drop-test/'${openflowPluginVersion}'/drop-test-'${openflowPluginVersion}'.jar'
mv drop-test-${openflowPluginVersion}.jar opendaylight/plugins

# 3. install Helium
heliumVersion=0.2.1-Helium-SR1
wget 'https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/distribution-karaf/'${heliumVersion}'/distribution-karaf-'${heliumVersion}'.zip'
unzip distribution-karaf-${heliumVersion}.zip
rm distribution-karaf-${heliumVersion}.zip
sed -i 's/0.0.0.0/127.0.0.1/g' distribution-karaf-${heliumVersion}/etc/org.apache.karaf.management.cfg

#run karaf-distribution
./distribution-karaf-${heliumVersion}/bin/karaf 

# run the follwing in opendaylight controller:
# opendaylight-user@root> feature:install odl-integration-compatible-with-all odl-dlux-all odl-openflowplugin-all odl-restconf odl-l2switch-switch odl-mdsal-apidocs odl-dlux-core 
#open firefox: http://127.0.0.1:8181/dlux/index.html
 



